//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.OpcionesLlamada = new HashSet<OpcionesLlamada>();
        }
    
        public int id_categoria { get; set; }
        public int nro_orden { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<OpcionesLlamada> OpcionesLlamada { get; set; }

        public CategoriaLlamada fromDomain()
        {
            return new CategoriaLlamada(this.nombre, this.nro_orden);
        }
    }
}
