//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Llamadas = new HashSet<Llamadas>();
        }
    
        public int id_cliente { get; set; }
        public Nullable<int> dni { get; set; }
        public string nombre { get; set; }
        public string nro_celular { get; set; }
    
        public virtual ICollection<Llamadas> Llamadas { get; set; }


        public Cliente fromDomain()
        {
            int DNI;
            if (this.dni is null) {DNI = 0;}
            else { DNI = (int) this.dni; }

            return new Cliente(DNI, this.nombre, this.nro_celular);
        }
    }
}
