//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Estados
    {
        public Estados()
        {
            this.CambiosEstado = new HashSet<CambiosEstado>();
        }

        public int id_estado { get; set; }
        public string nombre_estado { get; set; }

        public virtual ICollection<CambiosEstado> CambiosEstado { get; set; }

        internal EstadoLlamada fromDomain()
        {
            if (this.nombre_estado == "Iniciada") { return new Iniciada(this.nombre_estado); }
            if (this.nombre_estado == "EnCurso") { return new EnCurso(this.nombre_estado); }
            if (this.nombre_estado == "Finalizada") { return new Finalizada(this.nombre_estado); }

            return new Iniciada("");
        }

        static public Estados getEstadoDB(EstadoLlamada estado)
        {
            using (PPAI_DSIEntities db = new PPAI_DSIEntities())
            {
                string nombre = estado.getNombre();
                return db.Estados.Single(e => e.nombre_estado ==  nombre);
            }

        }
    }
}