//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    using System.Deployment.Application;
    using System.Linq;

    public partial class Llamadas
    {
        public Llamadas()
        {
            this.CambiosEstado = new HashSet<CambiosEstado>();
        }
    
        public int id_llamada { get; set; }
        public System.DateTime fecha_hora_inicio { get; set; }
        public string descripcion_operador { get; set; }
        public string detalle_accion_requerida { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<int> id_accion { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_subopcion { get; set; }
        public Nullable<int> id_opcion_llamada { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual ICollection<CambiosEstado> CambiosEstado { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual OpcionesLlamada OpcionesLlamada { get; set; }
        public virtual SubOpcionesLlamada SubOpcionesLlamada { get; set; }



        public Llamada fromDomain()
        {
            Cliente clienteLlamada;
            CambioEstado cambioEstadoActual;
            using (PPAI_DSIEntities db = new PPAI_DSIEntities())
            {
                clienteLlamada = db.Clientes
                    .Single(c => c.id_cliente == this.id_cliente)
                    .fromDomain();

                cambioEstadoActual = db.CambiosEstado
                    .ToList()
                    .Single(x => x.fecha_fin == null &&  x.id_llamada == this.id_llamada)
                    .fromDomain();
                    }

            return new Llamada(clienteLlamada,cambioEstadoActual,this.id_llamada);
        }

        static public void Update(Llamada llamada)
        {
            using (PPAI_DSIEntities db = new PPAI_DSIEntities())
            {
                //busca la llamada en la bd
                var llamada_bd = db.Llamadas.Single(l => l.id_llamada == llamada.id);

                //Actualiza los datos
                llamada_bd.descripcion_operador = llamada.getDescripcionOperador();
                llamada_bd.id_opcion_llamada = OpcionesLlamada.getAccionBD(llamada.getOpcion()).id_opcion_llamada;
                llamada_bd.id_subopcion = SubOpcionesLlamada.getSubOpcionBD(llamada.getSubOpcion()).id_subopcion;
                llamada_bd.duracion = (int)llamada.getDuracion();


                db.SaveChanges();
            }
        }
    }
}
