//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OpcionesLlamada
    {
        public OpcionesLlamada()
        {
            this.Llamadas = new HashSet<Llamadas>();
            this.SubOpcionesLlamada = new HashSet<SubOpcionesLlamada>();
            this.Validaciones = new HashSet<Validaciones>();
        }

        public int id_opcion_llamada { get; set; }
        public string nombre { get; set; }
        public int nro_orden { get; set; }
        public int id_categoria { get; set; }

        public virtual Categorias Categorias { get; set; }
        public virtual ICollection<Llamadas> Llamadas { get; set; }
        public virtual ICollection<SubOpcionesLlamada> SubOpcionesLlamada { get; set; }
        public virtual ICollection<Validaciones> Validaciones { get; set; }


        public OpcionLlamada fromDomain()
        {
            return new OpcionLlamada(this.nombre, this.nro_orden);
        }


        static public OpcionesLlamada getAccionBD(OpcionLlamada opcion)
        {
            using (PPAI_DSIEntities db = new PPAI_DSIEntities())
            {
                string nombre = opcion.getNombre();
                return db.OpcionesLlamada.Single(o => o.nombre == nombre);
            }
        }
    }
}
