//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubOpcionesLlamada
    {
        public SubOpcionesLlamada()
        {
            this.Llamadas = new HashSet<Llamadas>();
            this.Validaciones = new HashSet<Validaciones>();
        }
    
        public int id_subopcion { get; set; }
        public string nombre { get; set; }
        public int nro_orden { get; set; }
        public int id_opcion_llamada { get; set; }
    
        public virtual ICollection<Llamadas> Llamadas { get; set; }
        public virtual OpcionesLlamada OpcionesLlamada { get; set; }
        public virtual ICollection<Validaciones> Validaciones { get; set; }

        public SubOpcionLlamada fromDomain()
        {
            return new SubOpcionLlamada(this.nombre, this.nro_orden);
        }


        static public SubOpcionesLlamada getSubOpcionBD(SubOpcionLlamada subOpcion)
        {
            using (PPAI_DSIEntities db = new PPAI_DSIEntities())
            {
                string nombre = subOpcion.getNombre();
                return db.SubOpcionesLlamada.Single(so => so.nombre == nombre);
            }
        }
    }
}
