//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI2023
{
    using PPAI2023.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial class Validaciones
    {
        public Validaciones()
        {
            this.OpcionesValidaciones = new HashSet<OpcionesValidaciones>();
        }
    
        public int id_validacion { get; set; }
        public int nro_orden { get; set; }
        public string nombre { get; set; }
        public string mensaje_validacion { get; set; }
        public int id_opcion_llamada { get; set; }
        public Nullable<int> id_subopcion { get; set; }
    
        public virtual OpcionesLlamada OpcionesLlamada { get; set; }
        public virtual ICollection<OpcionesValidaciones> OpcionesValidaciones { get; set; }
        public virtual SubOpcionesLlamada SubOpcionesLlamada { get; set; }

        public Validacion fromDomain()
        {
            return new Validacion(this.nombre, this.mensaje_validacion, this.nro_orden);
        }
    }
}
